# Site Settings
baseurl: ""
url : "https://hschoi1104.github.io"

# Blog Settings
theme_settings :
  title : hschoi1104 Portfolio
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Hyunseok Choi
    description : ğŸ‘ŠJunior backend developer 
    experience :
      - start : 2020-05
        end : 2020-12
        experience : ì†Œí”„íŠ¸ì›¨ì–´ ë§ˆì—ìŠ¤íŠ¸ë¡œ 11ê¸° ìˆ˜ë£Œ
      - start : 2020-07
        end : 2020-07
        experience : ì „êµ­ ëŒ€í•™ìƒ í”„ë¡œê·¸ë˜ë° ë™ì•„ë¦¬ ì—°í•© UCPC ë³¸ì„  ì§„ì¶œ
      - start : 2019-07
        end : 2019-08
        experience : 2020 ì‚¼ì„± ëŒ€í•™ìƒ í”„ë¡œê·¸ë˜ë° ê²½ì§„ëŒ€íšŒ SCPC 2ì°¨ ì˜ˆì„  ì§„ì¶œ
      - start : 2019-11
        end : 2019-11
        experience : ACM-ICPC Seoul ë³¸ì„  ì§„ì¶œ, 23 Place
      - start : 2019-11
        end : 2019-11
        experience : ì œ 1íšŒ ê°€í†¨ë¦­ëŒ€í•™êµ í”„ë¡œê·¸ë˜ë° ê²½ì§„ëŒ€íšŒ CCPC ë¬¸ì œ ì¶œì œ
      - start : 2019-10
        end : 2019-10
        experience : 2019 ê°€í†¨ë¦­ëŒ€í•™êµ êµë‚´ í”„ë¡œê·¸ë˜ë° ëŒ€íšŒ ëŒ€ìƒğŸ† ìˆ˜ìƒ
      - start : 2019-07
        end : 2019-08
        experience : 2019 ì‚¼ì„± ëŒ€í•™ìƒ í”„ë¡œê·¸ë˜ë° ê²½ì§„ëŒ€íšŒ SCPC 1ì°¨ ì˜ˆì„  ì§„ì¶œ
      - start : 2019-07
        end : 2019-07
        experience : 2019 ì‚¼ì„± SDS í•˜ê³„ ëŒ€í•™ìƒ ì•Œê³ ë¦¬ì¦˜ íŠ¹ê°• ìˆ˜ë£Œ
      - start : 2018-10
        end : 2019-12
        experience : ê°€í†¨ë¦­ëŒ€í•™êµ ì•Œê³ ë¦¬ì¦˜ ì†Œëª¨ì„ ALCUK 3ê¸° íšŒì¥
      - start : 2018-06
        end : 2019-10
        experience : ê°€í†¨ë¦­ëŒ€í•™êµ ì•Œê³ ë¦¬ì¦˜ ì†Œëª¨ì„ ALCUK 2ê¸° ì„ì›
      - start : 2014-03
        experience : ê°€í†¨ë¦­ëŒ€í•™êµ ì»´í“¨í„°ì •ë³´ê³µí•™ë¶€ ì…í•™
    skills : 
      - skill : C,C++
        value : 70  # Percent value
      - skill : Java
        value : 70  # Percent value
      - skill : Javascript
        value : 70  # Percent value
      - skill : Algorithm
        value : 90  # Percent value
      - skill : Node.js
        value : 70  # Percent value
      - skill : Vue.js
        value : 50  # Percent value
      - skill : Spring boot
        value : 60  # Percent value
      - skill : Docker
        value : 70  # Percent value
      - skill : AWS
        value : 0  # Percent value

        
  # Icons
  icons :
    email:  hschoi1104@gmail.com
    linkedin:  # Full URL 
    github: hschoi1104
    gitlab:
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
